public class MapProductPrices {

    @AuraEnabled
    public String id{get; set;}
    @AuraEnabled
    public String link{get; set;}
    @AuraEnabled
    public String productId{get; set;}
    @AuraEnabled
    public String productLink{get; set;}
    @AuraEnabled
    public String productStatus{get; set;}
    @AuraEnabled
    public String name{get; set;}
    @AuraEnabled
    public String productName{get; set;}
    @AuraEnabled
    public String orderingNumber{get; set;}
    @AuraEnabled
    public Date validFrom{get; set;}
    @AuraEnabled
    public Boolean soldInWebShop{get; set;}
    @AuraEnabled
    public Boolean mapPricing{get; set;}
    @AuraEnabled
    public Decimal maxMapPricing{get; set;}
    @AuraEnabled
    public Decimal moq{get; set;}
    @AuraEnabled
    public Decimal priceSampleSize1{get; set;}
    @AuraEnabled
    public Decimal priceSampleSize10{get; set;}
    @AuraEnabled
    public Decimal priceSampleSize50{get; set;}
    @AuraEnabled
    public Decimal priceSampleSize100{get; set;}
    @AuraEnabled
    public Decimal priceSampleSize250{get; set;}
    @AuraEnabled
    public Decimal priceSampleSize500{get; set;}
    @AuraEnabled
    public Decimal priceSampleSize1000{get; set;}
    @AuraEnabled
    public String productCenter{get; set;}
    @AuraEnabled
    public String technology{get; set;}
    @AuraEnabled
    public String description{get; set;}
    @AuraEnabled
    public Decimal konditionsnummer_101{get; set;}
    @AuraEnabled
    public Decimal konditionsnummer_102{get; set;}
    @AuraEnabled
    public Decimal konditionsnummer_103{get; set;}
 

    public MapProductPrices()
    {
    }
}